name: Issue Add Assigness

on:
  issues:
    types: [opened, edited]

jobs:
  mark-duplicate:
    runs-on: ubuntu-latest
    steps:
      - uses: wow-actions/auto-comment@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          issuesOpened: |
            ğŸ‘‹ @{{ author }}ï¼Œæ„Ÿè°¢æ‚¨ç»™ FlyFish æå‡ºäº† issueã€‚
            è¯·æ ¹æ® issue æ¨¡ç‰ˆç¡®ä¿èƒŒæ™¯ä¿¡æ¯çš„å®Œå–„ï¼Œæˆ‘ä»¬å°†è°ƒæŸ¥å¹¶å°½å¿«å›å¤ä½ ã€‚
  mark-assignees:
    name: assign
    runs-on: ubuntu-latest
    steps:
      - name: mark assigness
        uses: actions-cool/issues-helper@v3
        with:
          actions: 'mark-assignees'
          token: ${{ secrets.GITHUB_TOKEN }}
          # issue-number: ${{ github.event.issue.number }}
          # assignees: jincheny
          # random-to: 1
          body: |
            â™¥ï¸ æœ‰åŠ³ @jincheny å°½å¿«ç¡®è®¤é—®é¢˜ ${{ github.event.issue.number }}ã€‚
            ç¡®è®¤æœ‰æ•ˆåå°†ä¸‹ä¸€æ­¥è®¡åˆ’å’Œå¯èƒ½éœ€è¦çš„æ—¶é—´å›å¤ç»™ @${{ github.event.issue.user.login }} ã€‚
            <!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->
          # number: ${{ github.event.issue.number }}
          # body-include: '<!-- AUTO_ASSIGENEES_NOTIFY_HOOK -->'
